semantic_models:
  #The name of the semantic model.
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    #The name of the dbt model and schema
    model: ref('products')
    #Entities. These usually corespond to keys in the table.
    entities:
      - name: product
        type: primary
        expr: product_id
    #Dimensions. Either categorical or time. These add additonal context to metrics. The typical querying pattern is Metric by Dimension.
    dimensions:
      - name: product_name
        type: categorical
        label: 商品名
        description: 商品の名称
      - name: product_type
        type: categorical
        label: 商品タイプ
        description: 商品のタイプ
      - name: product_description
        type: categorical
        label: 商品説明
        description: 商品の説明
      - name: is_food_item
        type: categorical
        label: 食べ物か？（True/False）
        description: 食べ物かどうかのフラグ
      - name: is_drink_item
        type: categorical
        label: 飲み物か？（True/False）
        description: 飲み物かどうかのフラグ
      - name: product_price
        type: categorical
        label: 商品単価
        description: 商品の単価
